version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/projects/My-Achievements-Site-BE/
file_exists_behavior: OVERWRITE
hooks:
  AfterInstall:
    - location: scripts/afterInstall.sh