version: '3'

services:
  nodejs:
    build: .
    container_name: my_achievements_app
    working_dir: /app
    ports:
      - ${NODEJS_EXTERNAL_PORT}:${NODEJS_PORT}
      - ${NODEMON_EXTERNAL_PORT}:${NODEMON_PORT}
    env_file:
      - ./.env
    volumes:
      - ./:/app
    networks:
      - default

  mongodb:
    image: mongo
    container_name: my_achievements_mongodb
    environment:
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_DB: ${MONGO_DB}
    volumes:
      - "./data/mongodb:/data/db"
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - ${MONGO_EXTERNAL_PORT}:${MONGO_PORT}
    env_file:
      - ./.env
    networks:
      - default

networks:
  default:
    driver: bridge
